// <auto-generated />
using System;
using EcoTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoTracker.Data.Migrations
{
    [DbContext(typeof(EcoTrackerDbContext))]
    partial class EcoTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoTracker.Models.CarbonEmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("EmissionTonsCO2")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OffsetTonsCO2")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ReferenceMonth")
                        .HasColumnType("int");

                    b.Property<int>("ReferenceYear")
                        .HasColumnType("int");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName");

                    b.HasIndex("Sector");

                    b.HasIndex("ReferenceYear", "ReferenceMonth");

                    b.ToTable("CarbonEmissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "EcoCorp Brasil",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Emissões do primeiro trimestre",
                            EmissionTonsCO2 = 1500.5m,
                            OffsetTonsCO2 = 300.0m,
                            ReferenceMonth = 1,
                            ReferenceYear = 2024,
                            Sector = "Energia"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "GreenTech Ltda",
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Emissões do datacenter",
                            EmissionTonsCO2 = 250.0m,
                            OffsetTonsCO2 = 100.0m,
                            ReferenceMonth = 2,
                            ReferenceYear = 2024,
                            Sector = "Tecnologia"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "AgroSustentavel SA",
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Emissões agrícolas Q1",
                            EmissionTonsCO2 = 3200.0m,
                            OffsetTonsCO2 = 1500.0m,
                            ReferenceMonth = 3,
                            ReferenceYear = 2024,
                            Sector = "Agronegócio"
                        });
                });

            modelBuilder.Entity("EcoTracker.Models.ComplianceAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ComplianceScore")
                        .HasColumnType("int");

                    b.Property<string>("CorrectiveActions")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Findings")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("NextAuditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuditDate");

                    b.HasIndex("CompanyName");

                    b.HasIndex("NormReference");

                    b.ToTable("ComplianceAudits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuditDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            AuditorName = "João Silva",
                            CompanyName = "EcoCorp Brasil",
                            ComplianceScore = 92,
                            CreatedAt = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Findings = "Conformidade elevada com pequenas observações",
                            NextAuditDate = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            NormReference = "ISO 14001:2015",
                            Result = "Approved"
                        },
                        new
                        {
                            Id = 2,
                            AuditDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            AuditorName = "Maria Oliveira",
                            CompanyName = "AgroSustentavel SA",
                            ComplianceScore = 75,
                            CorrectiveActions = "Implementar sistema de monitoramento contínuo",
                            CreatedAt = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Findings = "Necessita melhorias no controle de emissões",
                            NextAuditDate = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            NormReference = "ISO 14064:2018",
                            Result = "ConditionalApproval"
                        });
                });

            modelBuilder.Entity("EcoTracker.Models.EnvironmentalAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RelatedLicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName");

                    b.HasIndex("IsResolved");

                    b.HasIndex("Severity");

                    b.ToTable("EnvironmentalAlerts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlertType = "LicenseExpiration",
                            CompanyName = "EcoCorp Brasil",
                            CreatedAt = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsResolved = false,
                            Message = "Licença LIC-2024-001 expira em 30 dias",
                            RelatedLicenseNumber = "LIC-2024-001",
                            Severity = "High"
                        },
                        new
                        {
                            Id = 2,
                            AlertType = "EmissionThreshold",
                            CompanyName = "AgroSustentavel SA",
                            CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsResolved = false,
                            Message = "Emissão líquida acima do limite permitido para o setor",
                            Severity = "Critical"
                        });
                });

            modelBuilder.Entity("EcoTracker.Models.EnvironmentalLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuingAuthority")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName");

                    b.HasIndex("ExpirationDate");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("EnvironmentalLicenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "EcoCorp Brasil",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpirationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IssueDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IssuingAuthority = "IBAMA",
                            LicenseNumber = "LIC-2024-001",
                            LicenseType = "Licença de Operação",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "GreenTech Ltda",
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpirationDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IssueDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IssuingAuthority = "CETESB",
                            LicenseNumber = "LIC-2024-002",
                            LicenseType = "Licença Prévia",
                            Status = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
